### ISSUE TITLE
Package pdc-client for Fedora and EPEL7

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/pdc-client#11]
We'll need this in order to be able to deploy our pdc-updater project in Fedora Infrastructure.

**Comment by sochotnicky** [comment]
@ralphbean I _could_ sponsor one of the dev team and then go through review process with them. Or do you have other ways you'd like to do this?

**Comment by ralphbean** [comment]
That would work, @sochotnicky.  If that seems like it will be problematic, I could volunteer to maintain it once its up on PyPI.

**Comment by sochotnicky** [comment]
Considering we have https://apps.fedoraproject.org/packages/pdc-client I am closing this.
