### ISSUE TITLE
Cut a new upstream release please.

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/pdc-client#113]
It's been a while.  Can you cut a new upstream release, please?

**Comment by ralphbean** [comment]
(In particular, Fedora Infra would like the improvements to `ssl_verify`.)

**Comment by simozhan** [comment]
@ralphbean yeah. We have already planned the new release. It will happen in next week. Will let you know when it is finished.

**Comment by ralphbean** [comment]
Thanks.  Got another mention of this downstream here, btw:  https://pagure.io/pagure-dist-git/issue/20

**Comment by hluk** [comment]
Sorry, took longer than expected, but [pdc-client in Bodhi](https://bodhi.fedoraproject.org/updates/?packages=pdc-client) is finally in testing phase (awaiting +3 karma or 7 days to stable).
