### ISSUE TITLE
Current client breaks BeanBag syntax sugar for updates

### ISSUE THREAD

**Issue by lubomir** [product-definition-center/pdc-client#134]
Using the syntactic sugar for PATCH request gives an exception:

```python
> c = pdc_client.PDCClient('local')
> c['unreleasedvariants']['389-ds-1.2-20171009091843/'] += {'active': False}
TypeError: unsupported operand type(s) for +=: '_BeanBagWrapper' and 'dict'
```

Implementing the `__iadd__` method on `_BeanBagWrapper` similarly to existing methods makes the PATCH request work, but once that request finishes, another exception is reported:

```
TypeError: '_BeanBagWrapper' object does not support item assignment
```

For the PATCH use case this is harmless, but it indicates somehow a PUT request was attempted.  Indeed running `c['unreleasedvariants']['389-ds-1.2-20171009091843/'] = {'active': False}` (data is invalid, but it doesn't matter) reports the same problem and does not perform the request.

Adding a `__setitem__` fixes the PUT request.

However if both methods exist, issuing a PATCH with the first example fires a PATCH request followed immediately by PUT request that should not be there.

**Comment by xiangge** [comment]
BTW:
In this case, a ._ can also make the url end with /.
Like c['unreleasedvariants']['389-ds-1.2-20171009091843']._
