### ISSUE TITLE
Link to some API usage example from the README

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/pdc-client#7]
I'd like to use the python API from this if suitable.

Are there any example or docs for that living somewhere?  It doesn't have to be comprehensive.

**Comment by lubomir** [comment]
The documentation we have has not yet been moved into this repo (pull request #4). Unfortunately, for the time being the [old location](http://product-definition-center.github.io/product-definition-center/pdc_client.html) is also broken as it does not include the actual API.

Some examples:
- [a script used to find components with multiple contacts of same role](https://gist.github.com/lubomir/c78091bf286ee9764f99)
- [more complicated script for creating global components based on imported source RPMs](https://github.com/product-definition-center/product-definition-center/blob/master/pdc/scripts/create_release_components.py)

**Comment by ralphbean** [comment]
Ah ha, the [second example](https://github.com/product-definition-center/product-definition-center/blob/master/pdc/scripts/create_release_components.py) is _very_ close to what I was looking for.  Thanks!

**Comment by xychu** [comment]
The examples mentioned have been included as [examples](https://github.com/product-definition-center/pdc-client#examples) in README.

**Comment by ralphbean** [comment]
Cool, cool.  Thanks.
