### ISSUE TITLE
Upload releases to pypi

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/pdc-client#8]
Would be nice to be able to pip install this into a virtualenv for usage in other projects.

**Comment by xychu** [comment]
Any volunteer?
This is most about adding one `setup.py` file and distributed to pypi.

**Comment by sochotnicky** [comment]
@xychu Well I haven't done it before but I guess pypi should have some concept of organization too? I'd prefer if we didn't use anyone's personal pypi account for this? Apart from that I believe having it part of tito release should be mandatory

**Comment by xychu** [comment]
@sochotnicky neither do I...
I made my first comment based on
https://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#uploading-your-project-to-pypi
Also, from django-rest-framework's [release process](http://www.django-rest-framework.org/topics/project-management/#release-process), I think we could have multi maintainers that can push releases to pypi.
And IMPO, at first, we should keep pypi release just as an extra step in our release process, later after we have couples of succeed experiences, then it will be a good time to include the pypi distribution into the tito release.

**Comment by bliuredhat** [comment]
@xychu and  @sochotnicky , If who can teach me the ways how to do it , I want to have a try~.

**Comment by lubomir** [comment]
As far as I know, there are no organizations on PyPI. The person who first uploads a package is marked as Owner. Owners can add other people as Owners or Maintainers.
https://docs.python.org/2/distutils/packageindex.html#pypi-overview

**Comment by bliuredhat** [comment]
@lubomir , it's cool from your link~!  Can you build a issue in JIRA for me and I want to know the comment about this task.

**Comment by pypingou** [comment]
doing it, is as simple as `python setup.py sdist upload`, then in the UI the uploader can share the ACLs.

**Comment by ralphbean** [comment]
Any progress on this?  It makes development somewhat difficult.

**Comment by sochotnicky** [comment]
I'll get on it later today

**Comment by sochotnicky** [comment]
Created initial PR: https://github.com/product-definition-center/pdc-client/pull/23
And used it to create a release on pypi (I am aware the version numbers don't match, we'll sort it out):
https://pypi.python.org/pypi/pdc-client

I will note that current version is not really installable on empty box since the setup.py tries to import the source files which throws import error.

**Comment by ralphbean** [comment]
Cool.  Progress :)

**Comment by sochotnicky** [comment]
Closing since this is resolved and devs now have pypi pdc-client access
